version: "3"

services:

  app:
    container_name: remix-web
    build: .
    restart: unless-stopped
    command: ./entrypoint.sh
    volumes:
      - "storage:/home/sites/data"
    ports:
      - "5000:5000"
    networks:
      - web
      
  proxy:
    container_name: remix-proxy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/srv
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddydata:/data
      - caddyconfig:/config
    networks:
      - web
    depends_on:
      - app


networks:
  web:
    driver: bridge

volumes:
  storage:
  caddydata:
  caddyconfig:
